# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    event_image_directory:  'img/events/'

services:
    app.markdown:
        class: AppBundle\Utils\Markdown

    app.twig.markdown_extension:
        class:      AppBundle\Twig\MarkdownExtension
        arguments:  ['@app.markdown']
        public:     false
        tags:
            - { name: twig.extension }
